### ISSUE TITLE
Set up the basic Node files in the repository

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/slack-ghc#12]
## Description
As a user
I need to set up the basic node files of the repository.

### Update [Required]
- [ ] server.js
- [ ] package.json

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by Tharangi** [comment]
Assigned!

**Comment by kanmodi** [comment]
Closed #12!
