### ISSUE TITLE
Create Read Me file 

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/slack-ghc#13]
## Description
As a user
I need create a readme file

### Update [Required]
- [ ] readme.md

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours 
@Tharangi @kanmodi Please assign me this issue

**Comment by Tharangi** [comment]
Done

**Comment by kanmodi** [comment]
Closed #13
