### ISSUE TITLE
Add basic UI for the slack inviter

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/slack-ghc#14]
## Description
As a user
I need to develop basic UI of the slack inviter

## Mocks
![screenshot from 2018-07-07 10-12-09](https://user-images.githubusercontent.com/25412153/42406870-48f79f7c-81ce-11e8-9361-e258074e859a.png)

### Update [Required]
- [ ] main.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
6 hours 
@Tharangi @kanmodi  Please assign me this issue

**Comment by kanmodi** [comment]
Assigned! :)

**Comment by kanmodi** [comment]
Closed!
