### ISSUE TITLE
Create a template for the email

### ISSUE THREAD

**Issue by anumehaagrawal** [systers/slack-ghc#18]
## Description
As a user
I need  to create a template of how the email will look

## Mocks
![screenshot from 2018-07-12 00-02-46](https://user-images.githubusercontent.com/25412153/42592389-f7deec7a-8566-11e8-9a47-3989321797b0.png)

### Update [Required]
- [ ] server.js

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
16 hours 
@Tharangi @kanmodi  Can you please assign me this issue?

**Comment by kanmodi** [comment]
Assigned! :)

**Comment by kanmodi** [comment]
Closed #18!
