### ISSUE TITLE
Remove the Email Address label (Keep only the placeholder)

### ISSUE THREAD

**Issue by Tharangi** [systers/slack-ghc#27]
## Description
As a Systers community member,
I need to see a clean UI,
so that I can have a better user experience.

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ]  main.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.25 hours

**Comment by kanmodi** [comment]
Closed #27!
