### ISSUE TITLE
UI Update/CleanUp for GSoC18

### ISSUE THREAD

**Issue by ExactlyMay** [systers/slack-ghc#29]
## Description
As a [USER],
I need [TO DO THIS],
so that I can [ACCOMPLISH THAT].

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] [LIST ITEMS]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[INSERT NUMBER HERE] hours

**Comment by Rupinderwadali** [comment]
@ExactlyMay All the listed issues have been resolved. But we can still furnish the UI. Should we close this issue or make it open?
