### ISSUE TITLE
Add Code of Conduct, Terms and Privacy Policy Links

### ISSUE THREAD

**Issue by Tharangi** [systers/slack-ghc#31]
## Description
As a Systers community member,
I need to know the AnitaB's.org's Code of Conduct and Privacy Policy before agreeing to sign up for the Slack inviter,
so that I can be aware of how my data will be used and the expected behavior from me in this community.

## Mocks
By checking this box, I affirm that I have read and accept to be bound by the AnitaB.org [Code of Conduct](https://ghc.anitab.org/code-of-conduct/), [Terms](https://anitab.org/terms-of-use/), and [Privacy Policy](https://anitab.org/privacy-policy/). Further, I consent to the use of my information for the stated purpose.

### Update [Required]
- [ ] main.html

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by kanmodi** [comment]
Closed #31
