### ISSUE TITLE
Change the text of the contact in regard of issues in receiving the Slack inviter

### ISSUE THREAD

**Issue by Tharangi** [systers/slack-ghc#32]
## Description
As a Systers community member,
I need to see a proper message explaining what should I do in case of having issues with receiving an invite,
so that I can have a better user experience.

## Mocks
![image](https://user-images.githubusercontent.com/7287218/43879146-2ce11366-9bc0-11e8-99e7-d23eeeef73a2.png)

URL: http://communityhelp.anitab.org/portal

### Update [Required]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.25 hours

**Comment by Tharangi** [comment]
@anumehaagrawal it will take several minutes only to do this and #31 . Please try completing these before your final demo.

**Comment by kanmodi** [comment]
Closed #32!
