### ISSUE TITLE
No favicon in main page 

### ISSUE THREAD

**Issue by sarnava1** [systers/slack-ghc#42]
## Description
As a USER,
I need to see a favicon in the title bar along with title i.e GHC 2018.
The favicon is included in all websites and it makes the title bar complete along with the title.

## Mocks
At present there is no favicon in the title bar of the website.

![slackghcnofavioc](https://user-images.githubusercontent.com/25319565/46228089-b254d600-c37e-11e8-8963-2ad7e3e6c56d.png)

## Acceptance Criteria
There should be a favicon in the title bar. 

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
.5 hours

**Comment by sarnava1** [comment]
@anumehaagrawal @kanmodi @Tharangi please assign this to me.

**Comment by Tharangi** [comment]
@sarnava1 assigned to you.
