### ISSUE TITLE
No linting rules

### ISSUE THREAD

**Issue by f2015537** [systers/slack-ghc#45]
## Description
As a developer,
I need to add linting rules,
so that the code-base is more readable and maintainable. 

### Update [Required]
- [ ] Adding ESLint as a dev-dependency.
- [ ] Setting up the configuration for ESLint.
- [ ] Linting all the javascript files based on the above configuration.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1-2 hours

**Comment by f2015537** [comment]
@Tharangi @bethanyr @kanmodi @anumehaagrawal please assign this to me!

**Comment by bethanyr** [comment]
@f2015537 - Divyam - you can work on this issue.

**Comment by f2015537** [comment]
Thanks @bethanyr . I'm working on it.
