### ISSUE TITLE
The currentURL string parser is deprecated.

### ISSUE THREAD

**Issue by f2015537** [systers/slack-ghc#47]
![screenshot from 2018-10-01 03-17-26](https://user-images.githubusercontent.com/19348263/46263107-8ecd8f00-c528-11e8-8e65-7766db3917e8.png)

**Comment by f2015537** [comment]
@Tharangi @bethanyr please assign this to me! It just needs a slight modification to the mongoose.connect() method.

**Comment by bethanyr** [comment]
@f2015537 - I've assigned 1 issue to you already, I'll hold off on assigning more until that issue is resolved.
