### ISSUE TITLE
No meta tags for SEO

### ISSUE THREAD

**Issue by sarnava1** [systers/slack-ghc#48]
## Description
The site should have meta tags and ogp tags for better SEO. Having meta tags and ogp tags increase the score of our page and search engines rank it higher than other sites.

## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

**Comment by sarnava1** [comment]
@kanmodi @Tharangi @bethanyr @BaaniLeen @anumehaagrawal can you please assign this to me?

**Comment by Tharangi** [comment]
Assigned to you. Could you tell us what are the meta tags that you are planning to add?

**Comment by Tharangi** [comment]
What I wanted is just to know what are the meta keywords that you are going to use :)

**Comment by sarnava1** [comment]
The keywords can be: slack, slack-ghc, anita borg, systers, ghc, grassphopper celebrations, foss, open source, 2018 etc etc. Whatever word which is related to ghc can be used as a keyword. Please do suggest more keywords if you have something in mind.

**Comment by anumehaagrawal** [comment]
@sarnava1  Any updates on this PR ?

**Comment by sarnava1** [comment]
@anumehaagrawal  actually I am on a vacation and so could not fine a PR. As soon as I return home I will surely fine a PR. Thank you.

**Comment by sarnava1** [comment]
@anumehaagrawal I have opened a PR for this issue. Please review it.
