### ISSUE TITLE
Documentation update - linting instructions

### ISSUE THREAD

**Issue by f2015537** [systers/slack-ghc#62]
## Description
As a developer,
I need to constantly update the documentation(add linting instructions),
so that it reflects newly added features to the project.

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] README.md (Add instructions on how to lint javascript files.)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by Tharangi** [comment]
Hey @f2015537 , could you mention about the required update in the issue?

**Comment by f2015537** [comment]
@Tharangi I am claiming this issue.
