### ISSUE TITLE
Change Year from 2017 to 2018

### ISSUE THREAD

**Issue by shreyateeza** [systers/slack-ghc#7]
## Description 
There are many places where year 2017 needs to be replaced with year 2018. In many places it is written 17, so that too needs to be replaced with 18.

## Definition of Done
- [ ] Approval from 1 mentor

## Estimation
30 to 60 minutes

**Comment by shreyateeza** [comment]
@MeepyMay Please label this issue as `first-timers-only` and `Difficulty: Easy`.

**Comment by anumehaagrawal** [comment]
@Tharangi  Lets close this issue as the inviter is being revamped ?

**Comment by ExactlyMay** [comment]
Closing issue. Inviter's being updated and has the correct year in place.
