### ISSUE TITLE
Revamp index.html

### ISSUE THREAD

**Issue by shreyateeza** [systers/slack-ghc#8]
## Description
As a Systers community member,
I need to revamp the index.html,
so that it can provide much better user interface and experience.

## Mocks
![slack-inviter](https://user-images.githubusercontent.com/30488330/36945495-f0461b16-1fd4-11e8-9aee-9fe1d8b42cc8.png)

### Update [Required]
- [ ] Create a captcha.
- [ ] Create a "Code of Conduct" agreement.
- [ ] Create a GitHub login authentication.
 
### Enhancement to Update [Optional]
- [ ] Add alternate method to get slack invite, in case, the person does not have a github account.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
20 hours

**Comment by shreyateeza** [comment]
@MeepyMay Please review this issue and let me know if any amendments are required.

**Comment by shreyateeza** [comment]
@prachi1210 Please review this issue and let me know if any amendments are required.

**Comment by anumehaagrawal** [comment]
@Tharangi  Lets close this issue as this is already being worked on as a part of gsoc 18 ?

**Comment by ExactlyMay** [comment]
Closing as it's being worked on as part of gsoc18.
